### ISSUE TITLE
Account creation on ACMEv1 is disabled.

### ISSUE THREAD

**Issue by robversluis** [janeczku/rancher-letsencrypt#119]
LetsEncrypt client: Failed to register account: acme: Error 403 - urn:acme:error:unauthorized - Account creation on ACMEv1 is disabled. Please upgrade your ACME client to a version that supports ACMEv2 / RFC 8555. See https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430 for details.

**Comment by robversluis** [comment]
See https://github.com/eggsampler/acme

**Comment by fabinou** [comment]
Did you manage to make it work with Rancher ?

**Comment by vkruoso** [comment]
Im also looking for a solution to use in Rancher 1. Any ideas?

**Comment by TeslaSolari** [comment]
I know what is the issue is but not sure If the owner would patch this.

https://github.com/janeczku/rancher-letsencrypt/blob/09132310fd5bab0b80a7e1d17faca95f441c6a9a/letsencrypt/client.go#L19-L21

It's using the old API endpoint 80% sure if these were updated since it uses Lego that supports v2 it should work :?

**Comment by bkuhl** [comment]
For anyone still trying to do this, check out https://gist.github.com/fridgerator/db607d268f1f99329c8f9449e89abb4f

**Comment by digit81** [comment]
I have Rancher 1.4
Just had to change image from 
`janeczku/rancher-letsencrypt` 
to 
`vxcontrol/rancher-letsencrypt:v1.0.0`

Certificates are renewed now  :)

Thank you @bkuhl for pointing this instruction.

**Comment by SamMousa** [comment]
@robversluis if this issue is solved in v1.0.0, could you close it?
