### ISSUE TITLE
Check if domains has changed

### ISSUE THREAD

**Issue by kbrownlees** [janeczku/rancher-letsencrypt#2]
If you try to add a new domain to an existing certificate it is not detected it so no new certificate is issued. It still finds the certificate in the store and on rancher, so the result is a nop rather than the error about not managing an existing certificate.

**Comment by janeczku** [comment]
Thanks for your report!

The noop is expected behavior. The app was designed to manage **renewal** of a single certificate  issued **once** on first start of the service. In other words an instance of the service is tied to one specific certificate.
Consequently, to create a **new** certificate (e.g. one with different set of domains) one should create another service.
The next version will store configuration parameters in the metadata service instead of environmental variables, so users wont even be able to change the certificate parameters by upgrading the service in the UI.

That being said, do you think this approach is lacking in any way? Is there a need to change the certificate parameters after service deployment instead of just create another service?

**Comment by kbrownlees** [comment]
Thanks for the quick reply!

That does make total sense, and not being to upgrade the container will make that quite a lot clearer!

What is your opinion on the best way to handle losing a container (via an upgrade or a host going away)? Unless you have some form of external storage attached the recovery is a bit nasty since you have to delete the certificate from rancher - which you can't do until you take down the lb currently using it. If you go the external storage route, you need a different storage for each container or you hit the issue I raised initially - it doesn't realize when you change something.

Could add an option to force it to override the current certificate, this has the downside that two containers could race for the control of a cert. Or, could allow the name to be specified so you can just create a new certificate under a new name then migrate all the services across to at a convenient time.

**Comment by Fusion** [comment]
So, a clarification request: does this mean that every time I need to add a new certificate for a new domain I will need to run another instance from the catalog? If so, is there a way to add the new service to the existing letsencrypt stack? I don't believe rancher-compose could help in this case, right?

**Comment by janeczku** [comment]
@Fusion Yes, that is currently the idea. Anything else would require to implement some kind of  management web UI in rancher-letsencrypt itself which i am not fond of really.
> If so, is there a way to add the new service to the existing letsencrypt stack?
I like this. Unfortunately Rancher's catalog service does currently not allow to add a service to an existing stack. I think this would make a great feature request.

**Comment by janeczku** [comment]
@kbrownlees 
> What is your opinion on the best way to handle losing a container (via an upgrade or a host going away)?

Currently losing a container means that you will loose the ability to manage renewal of that certificate. This is because the app currently stores and reuses the original private key when requesting a certificate renewal. This was required because Rancher did previously not allow to overwrite the private key when updating a certificate resource. In the last Rancher release this has changed though. Hence we are not required anymore keep the certificate and key in storage, instead we would just track the state of the certificate using the Rancher API.
Theoretically this would allow us to "hijack" a certificate that was created by a previous instance of the service. I haven't made my mind up though how exactly to implement this. E.g., how do we determine if an existing certificate qualifies to be managed when you create a new instance of the service? The options i see are essentially what you already eluded to above.
1. By certificate name
User provides the name of certificate in the Catalog UI. When it matches an existing certificate the services will manage this one instead of creating a new resource.
2. By certificate CN/SAN
If there is any existing certificate issued by Let's Encrypt CA with the same domains the service will manage this resource instead of creating a new one. This has the clear disadvantage of a possible race over control of the same certificate by multiple services.

Any more suggestions?

**Comment by kbrownlees** [comment]
@Fusion you can use rancher compose to add another instance to the stack - just export the config and add a new section with the correct environment variables. May break in the future once environment variables are no longer used though.

@janeczku 

The current behaviour makes more sense knowing that you couldn't change private keys before! In terms of the options, both is probably best in terms of flexibility, with the custom name being optional? I can't see a way around the race condition, it is up to the user at the end of the day to not do something stupid :)

**Comment by janeczku** [comment]
@kbrownlees Decided to do option numero uno. See https://github.com/janeczku/rancher-letsencrypt/commit/644a843f26b83a61bc4934687bc9253e9f46a65d

**Comment by janeczku** [comment]
Image is should
