### ISSUE TITLE
Allow for custom containers to mount specific certificates

### ISSUE THREAD

**Issue by lalarsson** [janeczku/rancher-letsencrypt#6]
Currently only the LB is able to use the LE generated certificates, however one might want to use the generated certificates in other contexts (such as nginx SSL termination).

According to a [previously answered question](https://github.com/rancher/rancher/issues/4166#issuecomment-203029428) it's currently possible to mount the volume holding the certificates however this is, according to the answer, not going to be possible in the future.

I'd very much appreciate if I could use one LE container for all my certificates and would therefore like to be able to get the certificates directly from this one container.

**Comment by janeczku** [comment]
If i am not mistaken exposing them via Volume would mean that the containers consuming the certificate needs to run on the same host as the LE container. I wonder if there is a better approach like maybe add a simple HTTP service.

**Comment by smazurov** [comment]
What about consul or vault from hashi corp as certificate storage? Or tap into rancher API to grab certs from there?

**Comment by janeczku** [comment]
@smazurov Rancher API does not expose the private key for reading. I will consider Vault as an option.

**Comment by guruvan** [comment]
for a quick workaround, I've used the following 
```
#!/bin/bash
CERT_HOST=${CERT_HOST:-host.do.main}
for i in privateKey certificate 
  do grep $i /etc/letsencrypt/.acme/${CERT_HOST}.json | awk -F\" '{print $4}' | base64 --decode > /certs/${CERT_HOST}.$i
done 
cp /certs/${CERT_HOST}.privateKey /certs/host.do.mainr.key 
cp /certs/${CERT_HOST}.certificate /certs/host.do.main.crt
```

Dropping the recovered certs into consul or etcd is an excellent idea.

**Comment by EugenMayer** [comment]
@janeczku i would rather also add an "storage" option in the catalog or even a service-relation to a volume-container. Storage seems to make a lot of sense, then people can mount /etc/letsencrypt into on a specific host folder and then remount this in other services.

Using a volume-container can do the same with service links - nevertheless one of this options should be used in addition to v1/certificates API + fault - its far more easier to use in addition, doing the API way would need custom logic on containers which you might not want to change, since they are deployed using a stack or similar. A lot of those which support certs, do though support a "cert folder" to be mounted.

**Comment by janeczku** [comment]
@EugenMayer That makes a lot of sense. Vault is still on my list but shared storage will be implemented first.

**Comment by EugenMayer** [comment]
@janeczku i implemented the "path on the host" solution it here : https://github.com/EugenMayer/kontextwork-catalog/tree/master/templates/letsencrypt/2 

pick what you need, if you like. I tested it with portus as setup ( registry ) and i could get it working very easy., eventhoug portus/registry are rather complex, as they need those cert/priv key for token signing.

**Comment by EugenMayer** [comment]
@janeczku in production, this introduces a issues. Since the certificates are stored persistently, you run into a edge-case when updating the certificates when you e.g. add a additional domain like you described here: https://github.com/janeczku/rancher-letsencrypt/issues/14

The issues is, that it seems like /usr/bin/rancher-letsencrypt finds the certificates in letsencrypt and does not refetch them.

In my case, the certificate name is still the same, i just added a domain. So we need a proper "revalidation" if the certificate with name X stored in /etc/letsencrypt is really the one required by the catalog configuration. This could also make it possible to update the certificates without remaking the catalog ( just changing the ENV var ) - we should spin off an extra effort for this.

What i tried was then:
 - remove /etc/letsencrypts/production/certifactes/<name> - that does help

after a while the certificate is refetched using my "old account" - thats actually a pretty nice side-effect that we store the certificates.

**Comment by janeczku** [comment]
@EugenMayer 
Implemented [here](https://github.com/janeczku/rancher-letsencrypt/releases/tag/v0.3.0) and [here](https://github.com/rancher/community-catalog/pull/165).
Stored certificate is now evaluated against the list of DNS names in the `DOMAINS` envar.
You can specify host path or [Convoy volume](http://docs.rancher.com/rancher/latest/en/rancher-services/storage-service/) in which to mount the certificate folder (`/etc/letsencrypt/production/certs`). Certificates are now saved in a folder named after the certificate name instead of the CN domain name.

**Comment by EugenMayer** [comment]
that sounds pretty awesome. I will try my setup using your library and if all goes wrong, i will remove my fork, or report back. Great! 

I have build several solutions integrating this now. One Portus and one ApacheDS ( TLS ) using this stored certificates. Pretty neat

**Comment by janeczku** [comment]
@EugenMayer You can use https://github.com/janeczku/my-rancher-catalog.git. Be advised that the exposed volume contains only the production certificates.
