### ISSUE TITLE
Certificate generation doesn't work with Gandi v5 (new stable)

### ISSUE THREAD

**Issue by Dremor** [janeczku/rancher-letsencrypt#97]
There is a new version of the gandi service available in beta (https://beta.gandi.net/), which may have introduced some breaking changes. For now, rancher-letsencrypt don't work with this new version, as it uses a separate DNS, and a separate API server.

I would be cool to have  "Gandi-v5" or "Gandi-Beta" as new domain validation method, in order to test this before v5 is promoted to stable.

**Comment by CyrilSiman** [comment]
+1

**Comment by Dremor** [comment]
Gandi v5 have been promoted to stable.

V4 is still accessible here : https://v4.gandi.net/

**Comment by Dremor** [comment]
New API documentation : http://doc.livedns.gandi.net/

**Comment by tbaptista** [comment]
+1
This one could be easily solved by updating the lego external framework.

**Comment by SkYNewZ** [comment]
Is someone maintain this repo ?

**Comment by SkYNewZ** [comment]
After few hours of searching in gandi lib [xenolf/lego](https://github.com/xenolf/lego), I found [this issue](https://github.com/xenolf/lego/pull/365).
Apparently, this issue is fixed in at least https://github.com/xenolf/lego/releases/tag/v0.5.0 where we can found [the correct Gandi Live DNS API endpoint](https://github.com/xenolf/lego/blob/v0.5.0/providers/dns/gandiv5/gandiv5.go#L23).

So can you please update `lego` at least to version 5 ? Due to my change from OVH to Gandi, I am no longer able to use `janeczku/rancher-letsencrypt`... :cry:

**Comment by Dremor** [comment]
Closing issue as the repository didn't see any change for 5+ years, and without any answer from the dev.
